course/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm
app_name = 'course'

urlpatterns = [
    # auth
    path('account/register', views.register, name='register'),
    # path('account/login', auth_views.LoginView.as_view(template_name="registration/login.html",
    #                                                    authentication_form=UserLoginForm), name='login'),
    path('account/login', views.login_request, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    #course
    path('create-course/', views.CourseCreateView.as_view(), name='create'),
    path('my-course/', views.CourseListView.as_view(), name='my_courses'),
    path('<pk>/my-course/edit', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/my-course/delete', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module'),
]

onlinedars/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('', include('users.urls')),

]

urlpatterns += i18n_patterns(
    path('', include('course.urls')), prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='home'),
    path('<pk>/<slug>/module/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<pk>/profile/', views.UserDetailView.as_view(), name='user_profile'),
    path('<pk>/profile_edit', views.UpdateUserProfileView.as_view(), name='profile_edit'),
    path('permission/', views.PermissionView.as_view(), name = 'permission'),
    path('search/', views.course_search, name='post_search'),
]

templates/base.html
{% load static %}
{% load materializecss %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'materialize/css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>{% block title %}Homepage{% endblock %}</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}

    {% block content %}
        <main>
        </main>
    {% endblock %}
    {% include 'footer.html' %}

    <script src="{% static "materialize/js/jquery-3.5.1.min.js" %}"></script>
    <script src="{% static "materialize/js/materialize.js" %}"></script>

    <script>
        $(document).ready(function () {
            $(".sidenav").sidenav();
            $(".dropdown-trigger").dropdown();
            $('.modal').modal();
            $('select').formSelect();
            $('.collapsible').collapsible();
            $('select').formSelect();
        })
    </script>
</body>

</html>

templates/footer.html
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
    </div>
</footer>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script>
                $(document).ready(function(){
                    M.toast({html: "{{ message }}", classes: 'blue rounded'})
                })
            </script>
        {% elif message.tags == 'error' %}
            <script>
                $(document).ready(function(){
                    M.toast({html: "{{ message }}", classes: 'red rounded'})
                })
            </script>
        {% endif %}
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
{% load i18n %}
<header>
    <nav class="navbar-fixed nav">
        <div class="nav-wrapper container">
            <div class="container-fluid">
                <a href="{% url "users:home" %}" class="brand-logo">
                    logo
                </a>
                <a href="#" data-target="mobile-links" class="sidenav-trigger">
                  <i class="material-icons">menu</i>
                </a>
                <ul class="right hide-on-med-and-down">
                    <li>
                        <i class="material-icons right">search</i>
                    </li>
                    <li>
                        <form class="center" action="{% url "users:post_search" %}" method="GET">
                            <input id="search" type="search" name="query" placeholder="search for courses" >
                        </form>
                    </li>
                    {% for language in languages %}
                        <form action="" method="POST">
                            {% csrf_token %}
                            <li>
                                <input type="hidden" name="lang" value="{{ language.0 }}"/><br>
                                <input type="submit" class="btn btn-small black-text" value="{{ language.1 }}"/>
                            </li>
                        </form>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                        <ul id="dropdown1" class="dropdown-content">
                            <li><a href="{% url "course:my_courses" %}">{% trans 'My courses' %}</a></li>
                            <li><a href="{% url "users:user_profile" request.user.id %}">{% trans 'Profile' %}</a></li>
                            <li><a href="{% url 'course:create' %}">{% trans 'Create' %}</a></li>
                            <li class="divider"></li>
                            <li><a href="#modal1" class="modal-trigger">{% trans 'Log out' %}</a></li>
                        </ul>
                        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{ request.user.first_name }}<i class="material-icons right">arrow_drop_down</i></a></li>
                    {% else %}
                        <li><a href="{% url 'course:login' %}">{% trans 'Log in' %}</a></li>
                        <li><a href="{% url 'course:register' %}">{% trans 'Sign up' %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<ul class="sidenav" id="mobile-links">
    <li>
        <form action="#" method="GET">
            <input id="search" type="search" placeholder="search" name="query" required>
        </form>
    </li>
    <li><a href="#">Log in</a></li>
    <li><a href="#">Sign up</a></li>
</ul>

<!-- Modal Structure -->
<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Do you want to log out?</h4>
    </div>
    <div class="modal-footer">
        <a class="modal-close waves-effect waves-green btn-flat">Stay</a>
        <a href="{% url "course:logout" %}" class="modal-close waves-effect waves-green btn-flat">Log out</a>
    </div>
</div>