course/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm
app_name = 'course'

urlpatterns = [
    # auth
    path('account/register', views.register, name='register'),
    # path('account/login', auth_views.LoginView.as_view(template_name="registration/login.html",
    #                                                    authentication_form=UserLoginForm), name='login'),
    path('account/login', views.login_request, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    #course
    path('create-course/', views.CourseCreateView.as_view(), name='create'),
    path('my-course/', views.CourseListView.as_view(), name='my_courses'),
    path('<pk>/my-course/edit', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/my-course/delete', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module'),
]

onlinedars/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('', include('users.urls')),

]

urlpatterns += i18n_patterns(
    path('', include('course.urls')), prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='home'),
    path('<pk>/<slug>/module/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<pk>/profile/', views.UserDetailView.as_view(), name='user_profile'),
    path('<pk>/profile_edit', views.UpdateUserProfileView.as_view(), name='profile_edit'),
    path('permission/', views.PermissionView.as_view(), name = 'permission'),
    path('search/', views.course_search, name='post_search'),
]

templates/courses/course_manage/create-course.html
{% extends "base.html" %}

{% block title %}Create course{% endblock %}

{% block content %}
    <div class="course_form" style="padding: 10px 25px;margin-bottom: 255px; ">
        <h4>Create course</h4>
        <div class="divider"></div>
    {% if request.user.status == 'instructor' %}
        <form action="" method="POST" enctype="multipart/form-data"  style="padding: 10px 25px;">
            {% csrf_token %}
            <div class = "row">
                <div class="col s12 m7 l7">
                    <label>Subject</label>
                    {{ form.subject }}
                </div>
                <div class="col s12 m7 l7">
                    <label>Title</label>
                    {{ form.title }}
                </div>
                <div class="col s12 m7 l7">
                    <label>Slug</label>
                    {{ form.slug }}
                </div>
                <div class="col s12 m7 l7">
                    <label>Overview</label>
                    {{ form.overview }}
                </div>
                <div class="col s12 m7 l7">
                    <label>Upload cover image</label>
                    <div class = "file-field input-field">
                        <div class="waves-effect waves-light btn">
                            <span>Browse</span>
                            {{ form.cover }}
                        </div>
                    <div class = "file-path-wrapper">
                        <input class = "file-path" disabled type = "text"
                        placeholder = "Upload file" />
                    </div>
                    </div>
                </div>
                <div class="col s12 m7 l7">
                    <button class="waves-effect waves-light btn" type="submit">Create</button>
                </div>
            </div>
        </form>
    {% else %}
        <p class="flow-text">You don't have permission to create course, ask for <a href="{% url "users:permission" %}">permission</a>.</p>
    {% endif %}
    </div>
{% endblock %}

templates/courses/course_manage/delete_course.html
{% extends "base.html" %}

{% block title %}Delete course{% endblock %}

{% block content %}
    <div class="z-depth-1 center ">
        <p class="flow-text">Do you want to delete "{{ object.title }}" course ?</p>
        <form action="" method="POST" style="margin-bottom: 316px;">
            {% csrf_token %}
            <a href="{% url 'course:my_courses' %}" class="waves-effect waves-light btn-small green darken-2"><i class="material-icons left">cancel</i>Cancel</a>
            <button type="submit" class="waves-effect waves-light btn-small red"><i class="material-icons left">delete</i>Delete</button>
        </form>
    </div>
{% endblock %}

templates/courses/course_manage/my_courses.html
{% extends "base.html" %}

{% block title %}My courses{% endblock %}

{% block content %}
    <div class="my-courses" style="margin-bottom: 253px;">
        <h4>My courses</h4>
        <div class="divider"></div>
        <div class="row">
                {% for course in object_list %}
                    <div class="card blue-grey darken-1 col s10 m3 l3">
                        <div class="card-image">
                            <img src="{{ course.cover.url }}" width="200" height="200">
                        </div>
                        <div class="card-content white-text">
                            <span class="card-title">{{ course.title }}</span>
                            <p>{{ course.overview|truncatewords:10 }}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'course:course_edit' course.id %}">Edit</a>
                            <a href="{% url 'course:course_delete' course.id %}">Delete</a>
                            <a href="{% url 'course:course_module' course.id %}">Edit modules</a>
                        </div>
                    </div>
                {% empty %}
                    <p class="flow-text">You do not have any courses yet, <span><a href="{% url 'course:create' %}">create?</a></span></p>
                {% endfor %}
        </div>
    </div>
{% endblock %}