course/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm
app_name = 'course'

urlpatterns = [
    # auth
    path('account/register', views.register, name='register'),
    # path('account/login', auth_views.LoginView.as_view(template_name="registration/login.html",
    #                                                    authentication_form=UserLoginForm), name='login'),
    path('account/login', views.login_request, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    #course
    path('create-course/', views.CourseCreateView.as_view(), name='create'),
    path('my-course/', views.CourseListView.as_view(), name='my_courses'),
    path('<pk>/my-course/edit', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/my-course/delete', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module'),
]

onlinedars/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course.urls')),
    path('', include('users.urls')),

]

urlpatterns += i18n_patterns(
    path('', include('course.urls')), prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='home'),
    path('<pk>/<slug>/module/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<pk>/profile/', views.UserDetailView.as_view(), name='user_profile'),
    path('<pk>/profile_edit', views.UpdateUserProfileView.as_view(), name='profile_edit'),
    path('permission/', views.PermissionView.as_view(), name = 'permission'),
    path('search/', views.course_search, name='post_search'),
]

templates/users_temp/home_page.html
{% extends "base.html" %}
{% load static %}
{% block title%}Home page{% endblock %}

{% block content %}
    <div class="container row">
        <div class="col s12 m12 l12">
        <h3>The world's largest selection of courses</h3>
        <div class="divider"></div>
        <img class="responsive-img" src="{% static "web_imgs/main.png" %}" alt="" width="1200" height="400">
        </div>
    </div>
    <div class="courses" style="padding: 0 20px;">
        <h4>Latest courses</h4>
        <hr>
        <div class="row  border">
            {% for course in object_list %}
                <div class="col s12 m3 l3">
                    <div class="card small">
                        <div class="card-image waves-effect waves-block waves-light">
                            <img class="activator" src="{{ course.cover.url }}">
                        </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4"><strong>{{ course.title }}</strong><i class="material-icons right">more_vert</i></span>
                            <span class="grey-text">Instructor: {{ course.owner.first_name }}</span>
                            {% if request.user.is_authenticated %}
                                <p><a href="{% url 'users:course_detail' course.id course.slug %}">Learn</a></p>
                            {% else %}
                                <p><a href="{% url 'course:login' %}">Log in to enroll</a></p>
                            {% endif %}
                        </div>
                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">{{ course.title }}<i class="material-icons right">close</i></span>
                            <p>{{ course.overview }}</p>
                        </div>
                    </div>
                </div>
             {% endfor %}
        </div>
    </div>
{% endblock %}

templates/users_temp/module_list.html
{% extends "base.html" %}

{% block title %}{{ course.title }} modules{% endblock %}

{% block content %}
    <div class="container">
        <h3>Modules</h3>
        <div class="divider"></div>
    </div>
    <div class="">
        <div class="row" style="padding: 0 15px; margin-bottom: 150px;">
            <ul class="collapsible col s12 m7 l7">
                {% for module in  modules %}
                    <li>
                        <div class="collapsible-header">{{ module.title }}</div>
                        <div class="collapsible-body">
                            {% if module.description %}
                                <h4>About module</h4>
                                <p>{{ module.description|linebreaks }}</p>
                            {% endif %}
                          <div class="divider"></div>
                          <br>
                          {% if module.video %}
                              <video class="responsive-video center" width="750px" height="400px" controls src="{{ module.video.url }}"></video>
                          {% endif %}
                          <div class="divider"></div>
                          {% if module.file %}
                              <h4>Material for download</h4>
                              <p><a class="btn-small" href="{{ item.file.url }}"><i class="material-icons">download</i></a></p>
                          {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="col s12 m5 l5">
                <p class="flow-text"><span>Information about instructor</span></p>
                <table>
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <td>{{ course.owner.first_name }}</td>
                        </tr>
                        <tr>
                            <th>Last name</th>
                            <td>{{ course.owner.last_name }}</td>
                        </tr>
                        <tr>
                            <th>Age</th>
                            <td>{{ course.owner.age }}</td>
                        </tr>
                        <tr>
                            <th>Bio</th>
                            <td>{{ course.owner.bio }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
{% endblock %}

templates/users_temp/permission_form.html
{% extends "base.html" %}

{% block title %}Permission{% endblock %}

{% block content %}
    <div class="permission container z-depth-1" style="margin-bottom: 240px; margin-top: 25px;">
        <div class="form">
            <p>Please, send information about yourself</p>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn-small" type="submit" value="Send">
            </form>
        </div>
    </div>
{% endblock %}

templates/users_temp/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile{% endblock %}

{% block content %}
    <div class="profile" style="padding: 10px; margin-bottom: 100px;">
        <div class="row">
            <span class="flow-text">Profile information</span><a class="btn-small right" href="{% url "users:profile_edit" request.user.id %}">Edit</a>
            <div class="divider"></div>
            <br>
            <div class="col s12 m4 l4 border z-depth-1" style="padding: 15px;">
                <div class="center">
                    <img src="{{ user.picture.url }}" alt="" width="120" height="120" style="border: 1px transparent; border-radius: 50%;">
                    <hr>
                </div>
                <p><span><strong>First name:</strong> {{ user.first_name }}</span></p>
                <p><span><strong>Last name:</strong> {{ user.last_name }}</span></p>
                <span><strong>Status:</strong> <span class="blue white-text border">{{ user.status }}</span></span>
            </div>
            <div class="col s12 m1 l1"></div>
            <div class="col s12 m7 l7 border z-depth-1" style="padding: 15px;">
                <table>
                    <tbody>
                        <tr>
                            <th>Email</th>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <th>Age</th>
                            <td>{{ user.age }}</td>
                        </tr>
                        <tr>
                            <th>Phone number</th>
                            <td>{{ user.phone_number }}</td>
                        </tr>
                        <th>Bio</th>
                        <td><p>{{ course.owner.bio|linebreaks }}</p></td>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/users_temp/profile_edit.html
{% extends "base.html" %}

{% block title %}Edit profile{% endblock %}

{% block content %}
    <p class="flow-text">Profile settings</p>
    <div class="divider"></div>
    <div class="edit container z-depth-1" style="margin-top: 15px;">
        <div class="row"  >
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-field">
                    <label for="">First name</label>
                    {{ form.first_name}}
                </div>
                <div class="input-field">
                    <label for="">Last name</label>
                    {{ form.last_name}}
                </div>
                <div class="input-field">
                    <label for="">Age</label>
                    {{ form.age}}
                </div>
                <div class="input-field">
                    <label for="">Phone number</label>
                    {{ form.phone_number}}
                </div>
                <div class="input-field">
                    <label for="">Bio</label>
                    {{ form.bio}}
                </div>
                <div>
                    <label>Upload profile picture</label>
                    <div class = "file-field input-field">
                        <div class="waves-effect waves-light btn">
                            <span>Browse</span>
                            {{ form.picture }}
                        </div>
                    <div class = "file-path-wrapper">
                        <input class = "file-path" disabled type = "text"
                        placeholder = "Upload file" />
                    </div>
                    </div>
                </div>
                <button class="btn btn-small" type="submit" value="save">Save</button>
            </form>
        </div>
    </div>
    <br>
{% endblock %}

templates/users_temp/search.html
{% extends "base.html" %}

{% block title %}Results{% endblock %}

{% block content %}
    <div class="container">
        <div class="results" style="margin-bottom: 450px;">
            {% if query %}
                <h4>Courses containing "{{ query }}"</h4>
                <h6>
                    {% with results.count as total_results %}
                        Found {{ total_results }} result{{ total_results|pluralize }}
                    {% endwith %}
                </h6>
                <div class="row">
                {% for course in results %}
                    <div class="col s12 m3 l3">
                        <div class="card small">
                            <div class="card-image waves-effect waves-block waves-light">
                                <img class="activator" src="{{ course.cover.url }}">
                            </div>
                            <div class="card-content">
                                <span class="card-title activator grey-text text-darken-4"><strong>{{ course.title }}</strong><i class="material-icons right">more_vert</i></span>
                                <span class="grey-text">Instructor: {{ course.owner.first_name }}</span>
                                {% if request.user.is_authenticated %}
                                    <p><a href="{% url 'users:course_detail' course.id course.slug %}">Learn</a></p>
                                {% else %}
                                    <p><a href="{% url 'course:login' %}">Log in to enroll</a></p>
                                {% endif %}
                            </div>
                            <div class="card-reveal">
                                <span class="card-title grey-text text-darken-4">{{ course.title }}<i class="material-icons right">close</i></span>
                                <p>{{ course.overview }}</p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <p>Not found</p>
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}